import type { CVData } from "./cv-builder-types";

export interface StarterTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  defaultLayout: "professional" | "modern" | "classic" | "minimal";
  data: CVData;
}

const emptyBase: CVData = {
  personalInfo: {
    fullName: "",
    jobTitle: "",
    email: "",
    phone: "",
    location: "",
    website: "",
    summary: "",
  },
  experience: [],
  education: [],
  skills: [],
  projects: [],
  certifications: [],
  awards: [],
  references: [],
  volunteering: [],
  strengths: [],
  interests: [],
  publications: [],
  languages: [],
  socialLinks: [],
};

export const starterTemplates: StarterTemplate[] = [
  {
    id: "professional",
    name: "Professional",
    description: "Two-column layout with photo, skills grid, and achievements",
    icon: "P",
    defaultLayout: "professional",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Brion Silva",
        jobTitle: "Associate Technical Lead (Frontend)",
        email: "brionbmp@gmail.com",
        phone: "+94777933830",
        location: "Colombo, Sri Lanka",
        website: "www.brionmario.com",
        summary:
          "Frontend Developer with 5+ years of experience building scalable, high-performance web applications. Proficient in JavaScript, TypeScript, React, and tools like Redux, TailwindCSS, and Jest. Skilled in integrating REST APIs, WebSockets, and optimizing frontend performance. Currently contributing to WSO2's IAM products, focusing on frontend development and maintaining authentication SDKs used globally. Experienced in agile teams, solving complex problems, and balancing performance, security, and maintainability. Familiar with Docker, Kubernetes, and backend fundamentals like databases and security best practices.",
      },
      experience: [
        {
          id: "exp-1",
          jobTitle: "Associate Technical Lead (Frontend)",
          company: "WSO2",
          startDate: "05/2023",
          endDate: "Present",
          currentlyWorking: true,
          location: "Colombo, Sri Lanka",
          description: "Associate Technical Lead @ WSO2, Open-source technology provider.",
          highlights: [
            "Designed & implemented the system architecture of WSO2 Design System, Oxygen UI.",
            "Maintaining the Asgardeo JavaScript based Authentication SDKs.",
            "Implemented several feature like Tenant Management, Console Setting, etc.",
          ],
        },
        {
          id: "exp-2",
          jobTitle: "Senior Frontend Engineer",
          company: "WSO2",
          startDate: "06/2021",
          endDate: "05/2023",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "Senior Frontend Engineer @ WSO2, Open-source technology provider.",
          highlights: [
            "Implemented the key Branding feature of Asgardeo.",
            "Improved DX by creating a CLI for component scaffolding.",
            "Introduced NX as a replacement for Lerna to cut down build times by 40%.",
            "Designed a new architecture for the product with micro-frontends to improve the performance of the applications.",
            "Mentored and guided junior developers to ensure growth.",
            "Actively involved in the company hiring process and helped higher more than 20 candidates.",
            "Among the top 5% of high performers at WSO2 for the year 2022.",
          ],
        },
        {
          id: "exp-3",
          jobTitle: "Frontend Engineer",
          company: "WSO2",
          startDate: "07/2019",
          endDate: "06/2021",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "Frontend Engineer @ WSO2, Open-source technology provider.",
          highlights: [
            "Implemented Application Management, Consent Management and many more features in WSO2 Identity Server portals.",
            "Initiated the frontend integration test suite of onprem product covering more than 80% of scenarios.",
            "Migrated 2 legacy JSP apps to React.",
            "Developed more than 60% of the features for the WSO2 User Portal.",
            "Involved in demos like Forrester 2020, by developing frontend apps.",
          ],
        },
        {
          id: "exp-4",
          jobTitle: "Trainee Associate Software Engineer",
          company: "Zone24x7",
          startDate: "07/2017",
          endDate: "07/2018",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "Intern @ Zone247, Digital transformation partner specializing in IOT.",
          highlights: [
            "Built a compile-time plugin system for the Angular portals using Angular DevKit.",
            "Migrated Angular apps to AOT compiler, improving performance by over 75%.",
            "Worked on Java & .NET services of Matrix247 Agents.",
          ],
        },
      ],
      education: [
        {
          id: "edu-1",
          degree: "B.ENG(Hons) Software Engineering",
          institution: "University of Westminster",
          field: "Software Engineering",
          startDate: "09/2015",
          endDate: "07/2019",
          description: "",
        },
      ],
      skills: [
        { id: "s-1", name: "React" },
        { id: "s-2", name: "Typescript" },
        { id: "s-3", name: "JavaScript" },
        { id: "s-4", name: "CSS" },
        { id: "s-5", name: "SCSS" },
        { id: "s-6", name: "Node.js" },
        { id: "s-7", name: "Redux" },
        { id: "s-8", name: "Next.js" },
        { id: "s-9", name: "Storybook" },
        { id: "s-10", name: "Jest" },
        { id: "s-11", name: "React Testing Library" },
        { id: "s-12", name: "Cypress" },
        { id: "s-13", name: "Git" },
        { id: "s-14", name: "CI" },
        { id: "s-15", name: "Webpack" },
        { id: "s-16", name: "Tailwind" },
        { id: "s-17", name: "Agile" },
        { id: "s-18", name: "Accessibility" },
        { id: "s-19", name: "UX" },
        { id: "s-20", name: "OAuth2" },
        { id: "s-21", name: "OIDC" },
        { id: "s-22", name: "REST APIs" },
      ],
      awards: [
        {
          id: "aw-1",
          title: "University of Westminster Award",
          issuer: "University of Westminster",
          date: "2019",
          description: "Batch all-rounder for the academic year 2018/2019.",
        },
        {
          id: "aw-2",
          title: "National Best Quality ICT Awards NBQSA 2017",
          issuer: "NBQSA",
          date: "2017",
          description: "Awarded a merit prize for the Safe Plant project.",
        },
        {
          id: "aw-3",
          title: "Innoserve Awards 2017 Taipei, Taiwan",
          issuer: "Innoserve",
          date: "2017",
          description: "Won the silver award in the international category for the project Safe Plant.",
        },
      ],
      socialLinks: [
        { id: "sl-1", platform: "GitHub", url: "www.github.com/brionmario" },
        { id: "sl-2", platform: "Portfolio", url: "www.brionmario.com" },
        { id: "sl-3", platform: "LinkedIn", url: "www.linkedin.com/in/brionmario" },
        { id: "sl-4", platform: "Medium", url: "www.medium.com/@brionmario" },
      ],
      languages: [{ name: "English", proficiency: 4 }],
      projects: [],
      certifications: [],
      references: [],
      volunteering: [],
      strengths: [],
      interests: [],
      publications: [],
    },
  },
  {
    id: "blank",
    name: "Blank",
    description: "Start from scratch with an empty template",
    icon: "B",
    defaultLayout: "modern",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Your Name",
        jobTitle: "Your Job Title",
        email: "email@example.com",
        phone: "+1 (555) 123-4567",
        location: "City, Country",
        website: "www.example.com",
        summary: "Brief professional summary goes here.",
      },
    },
  },
  {
    id: "software-engineer",
    name: "Software Engineer",
    description: "Pre-filled template for software engineering roles",
    icon: "S",
    defaultLayout: "modern",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Alex Johnson",
        jobTitle: "Senior Software Engineer",
        email: "alex.johnson@email.com",
        phone: "+1 (555) 987-6543",
        location: "San Francisco, CA",
        website: "alexjohnson.dev",
        summary:
          "Full-stack software engineer with 6+ years of experience building web applications at scale. Expertise in React, Node.js, and cloud infrastructure. Passionate about clean architecture, developer experience, and mentoring teams.",
      },
      experience: [
        {
          id: "se-exp-1",
          jobTitle: "Senior Software Engineer",
          company: "TechCorp",
          startDate: "01/2022",
          endDate: "Present",
          currentlyWorking: true,
          location: "San Francisco, CA",
          description: "",
          highlights: [
            "Led migration of monolithic application to microservices architecture, improving deployment frequency by 300%.",
            "Designed and implemented real-time notification system serving 2M+ users.",
            "Mentored 4 junior engineers through structured 1:1 sessions and code reviews.",
          ],
        },
        {
          id: "se-exp-2",
          jobTitle: "Software Engineer",
          company: "StartupXYZ",
          startDate: "06/2019",
          endDate: "12/2021",
          currentlyWorking: false,
          location: "Remote",
          description: "",
          highlights: [
            "Built customer-facing dashboard from scratch, serving 50K+ daily active users.",
            "Reduced API response times by 60% through query optimization and caching strategies.",
            "Implemented CI/CD pipeline reducing deployment time from 2 hours to 15 minutes.",
          ],
        },
      ],
      education: [
        {
          id: "se-edu-1",
          degree: "B.S. Computer Science",
          institution: "Stanford University",
          field: "Computer Science",
          startDate: "09/2015",
          endDate: "06/2019",
          description: "",
        },
      ],
      skills: [
        { id: "se-s-1", name: "React" },
        { id: "se-s-2", name: "TypeScript" },
        { id: "se-s-3", name: "Node.js" },
        { id: "se-s-4", name: "Python" },
        { id: "se-s-5", name: "PostgreSQL" },
        { id: "se-s-6", name: "AWS" },
        { id: "se-s-7", name: "Docker" },
        { id: "se-s-8", name: "Kubernetes" },
        { id: "se-s-9", name: "GraphQL" },
        { id: "se-s-10", name: "Redis" },
        { id: "se-s-11", name: "Git" },
        { id: "se-s-12", name: "CI/CD" },
      ],
      languages: [
        { name: "English", proficiency: 5 },
        { name: "Spanish", proficiency: 3 },
      ],
    },
  },
  {
    id: "designer",
    name: "Designer",
    description: "Pre-filled template for UX/UI design roles",
    icon: "D",
    defaultLayout: "minimal",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Sam Rivera",
        jobTitle: "Senior UX/UI Designer",
        email: "sam.rivera@email.com",
        phone: "+1 (555) 234-5678",
        location: "New York, NY",
        website: "samrivera.design",
        summary:
          "Creative UX/UI designer with 5+ years of experience crafting intuitive digital experiences. Skilled in user research, prototyping, and design systems. Passionate about accessible and inclusive design that delights users.",
      },
      experience: [
        {
          id: "d-exp-1",
          jobTitle: "Senior UX/UI Designer",
          company: "DesignStudio",
          startDate: "03/2021",
          endDate: "Present",
          currentlyWorking: true,
          location: "New York, NY",
          description: "",
          highlights: [
            "Led redesign of flagship product resulting in 45% increase in user engagement.",
            "Built and maintained company-wide design system used by 30+ designers and developers.",
            "Conducted 100+ user interviews and usability testing sessions.",
          ],
        },
        {
          id: "d-exp-2",
          jobTitle: "UX Designer",
          company: "AgencyOne",
          startDate: "08/2018",
          endDate: "02/2021",
          currentlyWorking: false,
          location: "Brooklyn, NY",
          description: "",
          highlights: [
            "Designed end-to-end experiences for 15+ client projects across fintech and healthcare.",
            "Introduced design thinking workshops improving cross-team collaboration by 40%.",
            "Created interactive prototypes that reduced development iteration cycles by 50%.",
          ],
        },
      ],
      education: [
        {
          id: "d-edu-1",
          degree: "B.F.A. Interaction Design",
          institution: "Parsons School of Design",
          field: "Interaction Design",
          startDate: "09/2014",
          endDate: "05/2018",
          description: "",
        },
      ],
      skills: [
        { id: "d-s-1", name: "Figma" },
        { id: "d-s-2", name: "Sketch" },
        { id: "d-s-3", name: "Adobe XD" },
        { id: "d-s-4", name: "Prototyping" },
        { id: "d-s-5", name: "User Research" },
        { id: "d-s-6", name: "Design Systems" },
        { id: "d-s-7", name: "Wireframing" },
        { id: "d-s-8", name: "HTML/CSS" },
        { id: "d-s-9", name: "Accessibility" },
        { id: "d-s-10", name: "Motion Design" },
      ],
      languages: [
        { name: "English", proficiency: 5 },
        { name: "Portuguese", proficiency: 4 },
      ],
    },
  },
];
