import type { CVData } from "./cv-builder-types";

export interface StarterTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  defaultLayout: "professional" | "modern" | "classic" | "minimal";
  data: CVData;
}

const emptyBase: CVData = {
  personalInfo: {
    fullName: "",
    jobTitle: "",
    email: "",
    phone: "",
    location: "",
    website: "",
    summary: "",
  },
  experience: [],
  education: [],
  skills: [],
  projects: [],
  certifications: [],
  awards: [],
  references: [],
  volunteering: [],
  strengths: [],
  interests: [],
  publications: [],
  languages: [],
  socialLinks: [],
};

export const starterTemplates: StarterTemplate[] = [
  {
    id: "professional",
    name: "Professional",
    description: "Two-column layout with photo, skills grid, and achievements",
    icon: "P",
    defaultLayout: "professional",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Brion Silva",
        jobTitle: "Technical Lead",
        email: "brionbmp@gmail.com",
        phone: "+94777933830",
        location: "Colombo, Sri Lanka",
        website: "www.brionmario.com",
        summary:
          "<strong>Fullstack Engineer with 6+ years of experience</strong> in building scalable, high-performant and secure software solutions. Proficient in <strong>Frontend</strong> development, <strong>Backend</strong> development and <strong>Experience Design</strong>. Currently contributing to WSO2's IAM products, focusing on building secure and reliable platforms with <strong>Developer & User experience</strong> in mind.",
      },
      experience: [
        {
          id: "exp-1",
          jobTitle: "Technical Lead",
          company: "WSO2",
          startDate: "02/2025",
          endDate: "Present",
          currentlyWorking: true,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Was part of the IAM Core team overlooking the frontend development.",
            "Currently working on the WSO2's next generation IAM Platform i.e <a href='https://github.com/asgardeo/thunder' target='_blank'>Project Thunder</a>"
          ],
        },
        {
          id: "exp-2",
          jobTitle: "Associate Technical Lead",
          company: "WSO2",
          startDate: "05/2023",
          endDate: "02/2025",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Designed & implemented the system architecture of <strong>WSO2 Design System, Oxygen UI</strong>.",
            "Lead the Developer experience team maintaining the Asgardeo SDKs."
          ],
        },
        {
          id: "exp-3",
          jobTitle: "Senior Software Engineer",
          company: "WSO2",
          startDate: "06/2021",
          endDate: "05/2023",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Implemented the key <strong>Branding feature</strong> of Asgardeo.",
            "Among the <strong>top 5%</strong> of high performers at WSO2 for the year 2022.",
          ],
        },
        {
          id: "exp-4",
          jobTitle: "Software Engineer",
          company: "WSO2",
          startDate: "07/2019",
          endDate: "06/2021",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Implemented Application Management, Consent Management and many more features in WSO2 Identity Server portals.",
            "Involved in demos like <strong>Forrester 2020</strong>, by developing frontend apps.",
          ],
        },
        {
          id: "exp-5",
          jobTitle: "Trainee Associate Software Engineer",
          company: "Zone24x7",
          startDate: "07/2017",
          endDate: "07/2018",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Built a compile-time plugin system for the Angular portals using Angular DevKit.",
            "Worked on Java & .NET services of Matrix247 Agents.",
          ],
        },
      ],
      education: [
        {
          id: "edu-1",
          degree: "B.ENG(Hons) Software Engineering",
          institution: "University of Westminster",
          field: "Software Engineering",
          startDate: "09/2015",
          endDate: "07/2019",
          description: "",
        },
      ],
      skills: [
        { id: "s-1", name: "React" },
        { id: "s-2", name: "JavaScript/Typescript" },
        { id: "s-3", name: "Java" },
        { id: "s-4", name: "Go" },
        { id: "s-5", name: "Figma" },
        { id: "s-6", name: "Node.js" },
        { id: "s-8", name: "Next.js" },
        { id: "s-9", name: "Storybook" },
        { id: "s-10", name: "Vitest" },
        { id: "s-11", name: "Playwright" },
        { id: "s-13", name: "Git" },
        { id: "s-14", name: "CI" },
        { id: "s-15", name: "BuildTools" },
        { id: "s-16", name: "Tailwind" },
        { id: "s-17", name: "Agile" },
        { id: "s-18", name: "Accessibility" },
        { id: "s-19", name: "UX" },
        { id: "s-22", name: "REST APIs" },
      ],
      awards: [
        {
          id: "aw-1",
          title: "University of Westminster Award",
          issuer: "University of Westminster",
          date: "2019",
          description: "Batch all-rounder for the academic year 2018/2019.",
        },
        {
          id: "aw-2",
          title: "National Best Quality ICT Awards NBQSA 2017",
          issuer: "NBQSA",
          date: "2017",
          description: "Awarded a merit prize for the Safe Plant project.",
        },
        {
          id: "aw-3",
          title: "Innoserve Awards 2017 Taipei, Taiwan",
          issuer: "Innoserve",
          date: "2017",
          description: "Won the silver award in the international category for the project Safe Plant.",
        },
      ],
      socialLinks: [
        { id: "sl-1", platform: "GitHub", url: "www.github.com/brionmario" },
        { id: "sl-2", platform: "Portfolio", url: "www.brionmario.com" },
        { id: "sl-3", platform: "LinkedIn", url: "www.linkedin.com/in/brionmario" },
        { id: "sl-4", platform: "Medium", url: "www.medium.com/@brionmario" },
        { id: "sl-5", platform: "ResearchGate", url: "www.researchgate.net/profile/Brion-Mario" },
      ],
      languages: [{ name: "English", proficiency: 4 }, { name: "Sinhala", proficiency: 5 }],
      projects: [],
      certifications: [],
      references: [],
      volunteering: [],
      strengths: [],
      interests: [],
      publications: [{
        id: "pub-1",
        title: "Early Prediction of Cybersickness in Virtual, Augmented & Mixed Reality Applications: A Review",
        publisher: "International Conference for Convergence of Technology (I2CT)",
        date: "2019",
        link: "https://ieeexplore.ieee.org/document/9033650",
        description: "",
      },
    {
        id: "pub-2",
        title: "Kidney Transplant aftercare with IOT Medical Wearables",
        publisher: "",
        date: "2017",
        link: "https://www.researchgate.net/publication/327653042_Kidney_Transplant_aftercare_with_IOT_Medical_Wearables",
        description: "",
    }],
    },
  },
  {
    id: "blank",
    name: "Blank",
    description: "Start from scratch with an empty template",
    icon: "B",
    defaultLayout: "modern",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Your Name",
        jobTitle: "Your Job Title",
        email: "email@example.com",
        phone: "+1 (555) 123-4567",
        location: "City, Country",
        website: "www.example.com",
        summary: "Brief professional summary goes here. Use <strong>bold</strong> for emphasis and <em>italic</em> for subtle highlights.",
      },
    },
  },
  {
    id: "software-engineer",
    name: "Software Engineer",
    description: "Pre-filled template for software engineering roles",
    icon: "S",
    defaultLayout: "modern",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Alex Johnson",
        jobTitle: "Senior Software Engineer",
        email: "alex.johnson@email.com",
        phone: "+1 (555) 987-6543",
        location: "San Francisco, CA",
        website: "alexjohnson.dev",
        summary:
          "Full-stack software engineer with <strong>6+ years of experience</strong> building web applications at scale. Expertise in <em>React, Node.js</em>, and cloud infrastructure. Passionate about clean architecture, developer experience, and mentoring teams.",
      },
      experience: [
        {
          id: "se-exp-1",
          jobTitle: "Senior Software Engineer",
          company: "TechCorp",
          startDate: "01/2022",
          endDate: "Present",
          currentlyWorking: true,
          location: "San Francisco, CA",
          description: "",
          highlights: [
            "Led migration of monolithic application to <strong>microservices architecture</strong>, improving deployment frequency by <em>300%</em>.",
            "Designed and implemented real-time notification system serving <strong>2M+ users</strong>.",
            "Mentored <em>4 junior engineers</em> through structured 1:1 sessions and code reviews.",
          ],
        },
        {
          id: "se-exp-2",
          jobTitle: "Software Engineer",
          company: "StartupXYZ",
          startDate: "06/2019",
          endDate: "12/2021",
          currentlyWorking: false,
          location: "Remote",
          description: "",
          highlights: [
            "Built customer-facing dashboard from scratch, serving <strong>50K+ daily active users</strong>.",
            "Reduced API response times by <em>60%</em> through query optimization and caching strategies.",
            "Implemented <strong>CI/CD pipeline</strong> reducing deployment time from <em>2 hours to 15 minutes</em>.",
          ],
        },
      ],
      education: [
        {
          id: "se-edu-1",
          degree: "B.S. Computer Science",
          institution: "Stanford University",
          field: "Computer Science",
          startDate: "09/2015",
          endDate: "06/2019",
          description: "",
        },
      ],
      skills: [
        { id: "se-s-1", name: "React" },
        { id: "se-s-2", name: "TypeScript" },
        { id: "se-s-3", name: "Node.js" },
        { id: "se-s-4", name: "Python" },
        { id: "se-s-5", name: "PostgreSQL" },
        { id: "se-s-6", name: "AWS" },
        { id: "se-s-7", name: "Docker" },
        { id: "se-s-8", name: "Kubernetes" },
        { id: "se-s-9", name: "GraphQL" },
        { id: "se-s-10", name: "Redis" },
        { id: "se-s-11", name: "Git" },
        { id: "se-s-12", name: "CI/CD" },
      ],
      languages: [
        { name: "English", proficiency: 5 },
        { name: "Spanish", proficiency: 3 },
      ],
    },
  },
  {
    id: "designer",
    name: "Designer",
    description: "Pre-filled template for UX/UI design roles",
    icon: "D",
    defaultLayout: "minimal",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Sam Rivera",
        jobTitle: "Senior UX/UI Designer",
        email: "sam.rivera@email.com",
        phone: "+1 (555) 234-5678",
        location: "New York, NY",
        website: "samrivera.design",
        summary:
          "Creative UX/UI designer with <strong>5+ years of experience</strong> crafting intuitive digital experiences. Skilled in <em>user research, prototyping</em>, and design systems. Passionate about <strong>accessible and inclusive design</strong> that delights users.",
      },
      experience: [
        {
          id: "d-exp-1",
          jobTitle: "Senior UX/UI Designer",
          company: "DesignStudio",
          startDate: "03/2021",
          endDate: "Present",
          currentlyWorking: true,
          location: "New York, NY",
          description: "",
          highlights: [
            "Led redesign of flagship product resulting in <strong>45% increase</strong> in user engagement.",
            "Built and maintained company-wide <strong>design system</strong> used by <em>30+ designers and developers</em>.",
            "Conducted <strong>100+ user interviews</strong> and usability testing sessions.",
          ],
        },
        {
          id: "d-exp-2",
          jobTitle: "UX Designer",
          company: "AgencyOne",
          startDate: "08/2018",
          endDate: "02/2021",
          currentlyWorking: false,
          location: "Brooklyn, NY",
          description: "",
          highlights: [
            "Designed end-to-end experiences for <strong>15+ client projects</strong> across fintech and healthcare.",
            "Introduced design thinking workshops improving cross-team collaboration by <em>40%</em>.",
            "Created interactive prototypes that reduced development iteration cycles by <strong>50%</strong>.",
          ],
        },
      ],
      education: [
        {
          id: "d-edu-1",
          degree: "B.F.A. Interaction Design",
          institution: "Parsons School of Design",
          field: "Interaction Design",
          startDate: "09/2014",
          endDate: "05/2018",
          description: "",
        },
      ],
      skills: [
        { id: "d-s-1", name: "Figma" },
        { id: "d-s-2", name: "Sketch" },
        { id: "d-s-3", name: "Adobe XD" },
        { id: "d-s-4", name: "Prototyping" },
        { id: "d-s-5", name: "User Research" },
        { id: "d-s-6", name: "Design Systems" },
        { id: "d-s-7", name: "Wireframing" },
        { id: "d-s-8", name: "HTML/CSS" },
        { id: "d-s-9", name: "Accessibility" },
        { id: "d-s-10", name: "Motion Design" },
      ],
      languages: [
        { name: "English", proficiency: 5 },
        { name: "Portuguese", proficiency: 4 },
      ],
    },
  },
];
