import type { CVData } from "./cv-builder-types";
import { DEFAULT_SECTION_ORDER } from "./cv-builder-types";

export interface StarterTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  defaultLayout: "professional" | "modern" | "classic" | "minimal";
  data: CVData;
}

const emptyBase: CVData = {
  personalInfo: {
    fullName: "",
    jobTitle: "",
    email: "",
    phone: "",
    location: "",
    website: "",
    summary: "",
  },
  experience: [],
  education: [],
  skills: [],
  projects: [],
  certifications: [],
  awards: [],
  references: [],
  volunteering: [],
  strengths: [],
  interests: [],
  publications: [],
  languages: [],
  socialLinks: [],
  customSections: [],
  sectionOrder: DEFAULT_SECTION_ORDER,
};

export const starterTemplates: StarterTemplate[] = [
  {
    id: "professional",
    name: "Professional",
    description: "Two-column layout with photo, skills grid, and achievements",
    icon: "P",
    defaultLayout: "professional",
    // Fictional sample résumé. It intentionally fills every section the
    // Professional layout can render (photo, rich-text summary, a bulleted
    // experience with an inline link, three education entries, a skills grid,
    // achievements, publications, references and social links) so the canvas
    // and the PDF/HTML exports both have something to exercise.
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Jordan Avery",
        jobTitle: "Technical Lead",
        email: "jordan.avery@example.com",
        phone: "+94 (77) 123 4567",
        location: "Colombo, Sri Lanka",
        website: "www.jordanavery.dev",
        summary:
          "<strong>Fullstack Engineer with 7+ years of experience</strong> in building scalable, high-performant and secure software solutions. Proficient in <strong>Frontend</strong> development, <strong>Backend</strong> development and <strong>Experience Design</strong>. Currently contributing to identity and access management products, focusing on building secure and reliable platforms with <strong>Developer & User experience</strong> in mind.",
        // Vendored from https://avatar.vercel.sh/brion?rounded=60 — served
        // locally because that host sends no CORS header, and react-pdf has
        // to read the bytes to embed the photo in the PDF export.
        avatar: "/placeholder-avatar.png",
      },
      experience: [
        {
          id: "exp-1",
          jobTitle: "Technical Lead",
          company: "Northwind Labs",
          startDate: "02/2025",
          endDate: "Present",
          currentlyWorking: true,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Handled the open-source release process as part of the platform core team.",
            "Currently working on the next generation identity platform <a href='https://example.com' target='_blank'>Lighthouse</a>"
          ],
        },
        {
          id: "exp-2",
          jobTitle: "Associate Technical Lead",
          company: "Northwind Labs",
          startDate: "05/2023",
          endDate: "02/2025",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Designed & implemented the system architecture of the <strong>company design system</strong>.",
            "Lead the developer experience team maintaining the public SDKs."
          ],
        },
        {
          id: "exp-3",
          jobTitle: "Senior Software Engineer",
          company: "Northwind Labs",
          startDate: "06/2021",
          endDate: "05/2023",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Implemented the key <strong>Branding feature</strong> of the customer-facing console.",
            "Among the <strong>top 5%</strong> of high performers for the year 2022.",
          ],
        },
        {
          id: "exp-4",
          jobTitle: "Software Engineer",
          company: "Northwind Labs",
          startDate: "07/2019",
          endDate: "06/2021",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Implemented application management, consent management and many more features in the admin portals.",
            "Involved in flagship analyst demos, by developing frontend apps.",
          ],
        },
        {
          id: "exp-5",
          jobTitle: "Trainee Associate Software Engineer",
          company: "Vertex Systems",
          startDate: "07/2017",
          endDate: "07/2018",
          currentlyWorking: false,
          location: "Colombo, Sri Lanka",
          description: "",
          highlights: [
            "Built a compile-time plugin system for the Angular portals using Angular DevKit.",
            "Worked on Java & .NET services of the field-agent platform.",
          ],
        },
      ],
      education: [
        {
          id: "edu-1",
          degree: "B.ENG(Hons) Software Engineering",
          institution: "Riverside Institute of Technology",
          field: "Software Engineering",
          startDate: "09/2015",
          endDate: "07/2019",
          gpa: "1st Class Honors with an average of 84.8%",
          description: "",
        },
        {
          id: "edu-2",
          degree: "Secondary School Diploma",
          institution: "Lakeside College, Colombo, Sri Lanka",
          field: "Secondary Education",
          startDate: "2012",
          endDate: "",
          gpa: "1A 1C 2S",
          description: "",
        },
        {
          id: "edu-3",
          degree: "Secondary School Certificate",
          institution: "Lakeside College, Colombo, Sri Lanka",
          field: "Secondary Education",
          startDate: "2009",
          endDate: "",
          gpa: "5A 1B C3",
          description: "",
        },
      ],
      skills: [
        { id: "s-1", name: "React" },
        { id: "s-2", name: "JavaScript/Typescript" },
        { id: "s-3", name: "Java" },
        { id: "s-4", name: "Go" },
        { id: "s-5", name: "Figma" },
        { id: "s-6", name: "Node.js" },
        { id: "s-8", name: "Next.js" },
        { id: "s-9", name: "Storybook" },
        { id: "s-10", name: "Vitest" },
        { id: "s-11", name: "Playwright" },
        { id: "s-13", name: "Git" },
        { id: "s-14", name: "CI" },
        { id: "s-15", name: "BuildTools" },
        { id: "s-16", name: "Tailwind" },
        { id: "s-17", name: "Agile" },
        { id: "s-18", name: "Accessibility" },
        { id: "s-19", name: "UX" },
        { id: "s-22", name: "REST APIs" },
      ],
      awards: [
        {
          id: "aw-1",
          title: "Riverside Institute Award",
          issuer: "Riverside Institute of Technology",
          date: "2019",
          description: "Batch all-rounder for the academic year 2018/2019.",
        },
        {
          id: "aw-2",
          title: "National Software Quality Awards 2017",
          issuer: "National Software Quality Awards",
          date: "2017",
          description: "Awarded a merit prize for the SafeGrid project.",
        },
        {
          id: "aw-3",
          title: "International Innovation Awards 2017",
          issuer: "International Innovation Awards",
          date: "2017",
          description: "Won the silver award in the international category for the project SafeGrid.",
        },
      ],
      socialLinks: [
        { id: "sl-1", platform: "GitHub", url: "www.github.com/jordanavery" },
        { id: "sl-2", platform: "Portfolio", url: "www.jordanavery.dev" },
        { id: "sl-3", platform: "LinkedIn", url: "www.linkedin.com/in/jordanavery" },
        { id: "sl-4", platform: "Medium", url: "www.medium.com/@jordanavery" },
        { id: "sl-5", platform: "ResearchGate", url: "www.researchgate.net/profile/Jordan-Avery" },
      ],
      languages: [],
      projects: [],
      certifications: [],
      references: [
        {
          id: "ref-1",
          name: "Morgan Ellis",
          title: "Chief Operating Officer (COO)",
          company: "Brightpath Ltd",
          email: "morgan.ellis@example.com",
          phone: "+94 (76) 234 5678",
        },
        {
          id: "ref-2",
          name: "Priya Raman",
          title: "Senior Lecturer",
          company: "Riverside Institute of Technology",
          email: "priya.raman@example.edu",
          phone: "+94 (77) 345 6789",
        },
      ],
      volunteering: [],
      strengths: [],
      interests: [],
      publications: [{
        id: "pub-1",
        title: "Early Prediction of Motion Sickness in Mixed Reality Applications: A Review",
        publisher: "International Conference on Emerging Technology (ICET)",
        date: "2019",
        link: "https://example.com/publications/mixed-reality-review",
        description: "",
      },
    {
        id: "pub-2",
        title: "Post-Transplant Aftercare with IoT Medical Wearables",
        publisher: "",
        date: "2017",
        link: "https://example.com/publications/iot-medical-wearables",
        description: "",
    }],
    },
  },
  {
    id: "blank",
    name: "Blank",
    description: "Start from scratch with an empty template",
    icon: "B",
    defaultLayout: "modern",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Your Name",
        jobTitle: "Your Job Title",
        email: "email@example.com",
        phone: "+1 (555) 123-4567",
        location: "City, Country",
        website: "www.example.com",
        summary: "Brief professional summary goes here. Use <strong>bold</strong> for emphasis and <em>italic</em> for subtle highlights.",
      },
    },
  },
  {
    id: "software-engineer",
    name: "Software Engineer",
    description: "Pre-filled template for software engineering roles",
    icon: "S",
    defaultLayout: "modern",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Alex Johnson",
        jobTitle: "Senior Software Engineer",
        email: "alex.johnson@email.com",
        phone: "+1 (555) 987-6543",
        location: "San Francisco, CA",
        website: "alexjohnson.dev",
        summary:
          "Full-stack software engineer with <strong>7+ years of experience</strong> building web applications at scale. Expertise in <em>React, Node.js</em>, and cloud infrastructure. Passionate about clean architecture, developer experience, and mentoring teams.",
      },
      experience: [
        {
          id: "se-exp-1",
          jobTitle: "Senior Software Engineer",
          company: "TechCorp",
          startDate: "01/2022",
          endDate: "Present",
          currentlyWorking: true,
          location: "San Francisco, CA",
          description: "",
          highlights: [
            "Led migration of monolithic application to <strong>microservices architecture</strong>, improving deployment frequency by <em>300%</em>.",
            "Designed and implemented real-time notification system serving <strong>2M+ users</strong>.",
            "Mentored <em>4 junior engineers</em> through structured 1:1 sessions and code reviews.",
          ],
        },
        {
          id: "se-exp-2",
          jobTitle: "Software Engineer",
          company: "StartupXYZ",
          startDate: "06/2019",
          endDate: "12/2021",
          currentlyWorking: false,
          location: "Remote",
          description: "",
          highlights: [
            "Built customer-facing dashboard from scratch, serving <strong>50K+ daily active users</strong>.",
            "Reduced API response times by <em>60%</em> through query optimization and caching strategies.",
            "Implemented <strong>CI/CD pipeline</strong> reducing deployment time from <em>2 hours to 15 minutes</em>.",
          ],
        },
      ],
      education: [
        {
          id: "se-edu-1",
          degree: "B.S. Computer Science",
          institution: "Stanford University",
          field: "Computer Science",
          startDate: "09/2015",
          endDate: "06/2019",
          description: "",
        },
      ],
      skills: [
        { id: "se-s-1", name: "React" },
        { id: "se-s-2", name: "TypeScript" },
        { id: "se-s-3", name: "Node.js" },
        { id: "se-s-4", name: "Python" },
        { id: "se-s-5", name: "PostgreSQL" },
        { id: "se-s-6", name: "AWS" },
        { id: "se-s-7", name: "Docker" },
        { id: "se-s-8", name: "Kubernetes" },
        { id: "se-s-9", name: "GraphQL" },
        { id: "se-s-10", name: "Redis" },
        { id: "se-s-11", name: "Git" },
        { id: "se-s-12", name: "CI/CD" },
      ],
      languages: [
        { name: "English", proficiency: 5 },
        { name: "Spanish", proficiency: 3 },
      ],
    },
  },
  {
    id: "designer",
    name: "Designer",
    description: "Pre-filled template for UX/UI design roles",
    icon: "D",
    defaultLayout: "minimal",
    data: {
      ...emptyBase,
      personalInfo: {
        fullName: "Sam Rivera",
        jobTitle: "Senior UX/UI Designer",
        email: "sam.rivera@email.com",
        phone: "+1 (555) 234-5678",
        location: "New York, NY",
        website: "samrivera.design",
        summary:
          "Creative UX/UI designer with <strong>5+ years of experience</strong> crafting intuitive digital experiences. Skilled in <em>user research, prototyping</em>, and design systems. Passionate about <strong>accessible and inclusive design</strong> that delights users.",
      },
      experience: [
        {
          id: "d-exp-1",
          jobTitle: "Senior UX/UI Designer",
          company: "DesignStudio",
          startDate: "03/2021",
          endDate: "Present",
          currentlyWorking: true,
          location: "New York, NY",
          description: "",
          highlights: [
            "Led redesign of flagship product resulting in <strong>45% increase</strong> in user engagement.",
            "Built and maintained company-wide <strong>design system</strong> used by <em>30+ designers and developers</em>.",
            "Conducted <strong>100+ user interviews</strong> and usability testing sessions.",
          ],
        },
        {
          id: "d-exp-2",
          jobTitle: "UX Designer",
          company: "AgencyOne",
          startDate: "08/2018",
          endDate: "02/2021",
          currentlyWorking: false,
          location: "Brooklyn, NY",
          description: "",
          highlights: [
            "Designed end-to-end experiences for <strong>15+ client projects</strong> across fintech and healthcare.",
            "Introduced design thinking workshops improving cross-team collaboration by <em>40%</em>.",
            "Created interactive prototypes that reduced development iteration cycles by <strong>50%</strong>.",
          ],
        },
      ],
      education: [
        {
          id: "d-edu-1",
          degree: "B.F.A. Interaction Design",
          institution: "Parsons School of Design",
          field: "Interaction Design",
          startDate: "09/2014",
          endDate: "05/2018",
          description: "",
        },
      ],
      skills: [
        { id: "d-s-1", name: "Figma" },
        { id: "d-s-2", name: "Sketch" },
        { id: "d-s-3", name: "Adobe XD" },
        { id: "d-s-4", name: "Prototyping" },
        { id: "d-s-5", name: "User Research" },
        { id: "d-s-6", name: "Design Systems" },
        { id: "d-s-7", name: "Wireframing" },
        { id: "d-s-8", name: "HTML/CSS" },
        { id: "d-s-9", name: "Accessibility" },
        { id: "d-s-10", name: "Motion Design" },
      ],
      languages: [
        { name: "English", proficiency: 5 },
        { name: "Portuguese", proficiency: 4 },
      ],
    },
  },
];
